name: udemy_intermediatework
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  logging: ^1.0.2
  flutter:
    sdk: flutter

  get: ^4.6.6
  # moor_flutter: ^4.0.0
  # sqflite: ^2.3.3+1
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  supabase_flutter: ^2.6.0
  path_provider: ^2.1.4

dev_dependencies:
  # hive_generator: ^2.0.0
  # moor_generator: 4.6.0+1
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
